### ISSUE TITLE
hangs on some files

### ISSUE THREAD

**Issue by vankasteelj** [buzz/mediainfo.js#2]
I'm encountering this error with one of the files. the original lib (non-js) works fine on that same file.
```
Uncaught abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 536870912, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (file:///media/vankasteelj/WD500/GIT/opensubtitles-uploader/app/js/vendor/mediainfo.js:1:22392)
    at stackTrace (file:///media/vankasteelj/WD500/GIT/opensubtitles-uploader/app/js/vendor/mediainfo.js:1:22575)
    at abort (file:///media/vankasteelj/WD500/GIT/opensubtitles-uploader/app/js/vendor/mediainfo.js:9:13967)
    at abortOnCannotGrowMemory (file:///media/vankasteelj/WD500/GIT/opensubtitles-uploader/app/js/vendor/mediainfo.js:1:22935)
    at enlargeMemory (file:///media/vankasteelj/WD500/GIT/opensubtitles-uploader/app/js/vendor/mediainfo.js:1:23380)
    at Function.Runtime.dynamicAlloc (file:///media/vankasteelj/WD500/GIT/opensubtitles-uploader/app/js/vendor/mediainfo.js:1:6849)
    at _sbrk (file:///media/vankasteelj/WD500/GIT/opensubtitles-uploader/app/js/vendor/mediainfo.js:1:73610)
    at Mta (file:///media/vankasteelj/WD500/GIT/opensubtitles-uploader/app/js/vendor/mediainfo.js:1:1052160)
    at Spa (file:///media/vankasteelj/WD500/GIT/opensubtitles-uploader/app/js/vendor/mediainfo.js:1:940060)
    at Yua (file:///media/vankasteelj/WD500/GIT/opensubtitles-uploader/app/js/vendor/mediainfo.js:1:1099625)
```

it hangs for about 2min (on i5 4670k, 16gb ram), then prints that error. I'm using node, but on your test website it acts the same (freezing the entire browser)

**Comment by buzz** [comment]
This is an out of memory condition. The solution is to increase the `TOTAL_MEMORY` value. This has to be done at [compile time](https://github.com/buzz/mediainfo.js/blob/master/build.sh#L6).
I set it to 512 MiB which is apparently not enough for all files.

Apart from that I'd suggest to use the native lib through some binding if that is possible for your project. The emscripten port is not as fast and probably not as stable.

**Comment by vankasteelj** [comment]
I was trying your thing because I currently spawn the library directly from node (`require('child_process').exec`), and it's not really "clean". But it works, for sure. I just thought I'd report this.

**Comment by vankasteelj** [comment]
and if 512mb is not enough, then it probably means that on that specific file (.avi) it's trying to get the end of the file (maybe for framecount, or duration) and it cannot, as it has to load the entire file (1gb) in memory. Most probably a buggy avi file, but it works with native^^

**Comment by buzz** [comment]
Yes, it's true. Sometimes files need to be parsed until the end. But it is not necessary to load the entire file to memory at once.

If you are using the `open` function the library actually loads the whole file to memory. But you should use `open_buffer_init(...)`/`open_buffer_continue(...)` to parse data [chunk by chunk](https://github.com/buzz/mediainfo.js/blob/gh-pages/js/mediainfopage.js#L113).

I tested the emscripten port successfully with 10 GB files and larger and it never used more than 512 MB.
